Repository timerring/bilive, pull requests merged in 2025-03, with the labels that each got.

#184 fix: fix referenced issue
  src/burn/only_render.py
Labels: bug fix

#190 feat: redesign the log module
  logs/burningLog/.gitkeep
  logs/mergeLog/.gitkeep
  logs/scanLog/.gitkeep
  logs/uploadLog/.gitkeep
  scan.sh
  src/burn/generate_danmakus.py
  src/burn/generate_subtitles.py
  src/burn/only_render.py
  src/burn/render_and_merge.py
  src/burn/render_video.py
  src/burn/scan.py
  src/config.py
  src/log/__init__.py
  src/log/logger.py
  src/subtitle/generate.py
  src/upload/query_search_suggestion.py
  src/upload/upload.py
  src/utils/clearLogs.sh
  src/utils/removeEmojis.py
  upload.sh
Labels: feature

#191 fix: retain runtime logs
  logs/blrec/.gitkeep
  logs/runtime/.gitkeep
  record.sh
  scan.sh
  settings.toml
  src/config.py
  upload.sh
Labels: enhancement

#198 build: release new version
  .dockerignore
  Dockerfile
  README.md
Labels: enhancement

#212 Add default tags if no suggestions were returned
  src/upload/extract_video_info.py
Labels: enhancement

#217 build: release docker with gpu
  Dockerfile-GPU
  README.md
Labels: build

#222 Add Docker Compose file
  README.md
  compose.yml
  docs/installation.md
Labels: build

#240 revert: reserve the folder
  .dockerignore
  .gitignore
  Videos/.gitkeep
Labels: enhancement

#241 feat: custom title and description
  README.md
  src/config.py
  src/upload/extract_video_info.py
Labels: enhancement

#242 feat: add gift filter
  src/config.py
  src/danmaku/adjust_price.py
Labels: enhancement

#234 fix & feat: use sqlite to track upload queue and add re-upload when last upload task failed
  .gitignore
  requirements.txt
  src/burn/render_then_merge.py
  src/burn/render_video.py
  src/config.py
  src/db/__init__.py
  src/db/conn.py
  src/upload/upload.py
Labels: feature
