Repository timerring/bilive, pull requests merged in 2025-04, with the labels that each got.

#247 fix: adjust login method
  README.md
  src/upload/upload.py
Labels: bug, enhancement

#250 feat: add gemini mllm
  README.md
  src/autoslice/mllm_sdk/gemini_sdk.py
  src/autoslice/mllm_sdk/zhipu_sdk.py
  src/autoslice/title_generator.py
  src/burn/render_video.py
  src/config.py
Labels: feature

#251 feat: add qwen mllm
  README.md
  assets/qwen-color.svg
  src/autoslice/mllm_sdk/qwen_sdk.py
  src/autoslice/title_generator.py
  src/config.py
Labels: feature

#252 feat: add whisper api
  README.md
  src/burn/render_command.py
  src/burn/render_queue.py
  src/burn/render_then_merge.py
  src/burn/render_video.py
  src/config.py
  src/subtitle/api/whisper_sdk.py
  src/subtitle/generate_subtitles.py
  src/subtitle/subtitle_generator.py
  src/upload/generate_upload_data.py
  src/upload/upload.py
Labels: feature

#253 refactor: adjust rendering logic
  src/burn/render_command.py
Labels: enhancement

#256 fix: update blrec and resolve conflicts
  requirements.txt
  src/autoslice/mllm_sdk/gemini_new_sdk.py
  src/autoslice/mllm_sdk/gemini_old_sdk.py
  src/autoslice/title_generator.py
Labels: enhancement

#260 fix: add retry process
  settings.toml
  src/db/conn.py
  src/log/retry.py
  src/upload/upload.py
Labels: bug fix

#261 feat: cover generation
  README.md
  assets/minimax-color.svg
  assets/minimax-text.svg
  settings.toml
  src/config.py
  src/cover/__init__.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/minimax_sdk.py
  src/log/retry.py
  src/upload/upload.py
Labels: feature

#262 feat: kwai kolors
  README.md
  assets/siliconcloud-color.svg
  assets/siliconcloud-text.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/kolors_sdk.py
  src/cover/image_model_sdk/minimax_sdk.py
Labels: feature

#263 feat: tencent hunyuan
  README.md
  assets/hunyuan-color.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/tencent_sdk.py
Labels: feature

#264 feat: baidu ernie
  README.md
  assets/wenxin-color.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/baidu_sdk.py
Labels: feature

#265 feat: stable diffusion
  README.md
  assets/stability-brand-color.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/baidu_sdk.py
  src/cover/image_model_sdk/stability_sdk.py
Labels: feature

#266 feat: luma photon
  README.md
  assets/luma-color.svg
  assets/luma-text.svg
  bilive.toml
  requirements.txt
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/luma_sdk.py
Labels: feature

#267 feat: ideogram v2
  README.md
  assets/ideogram.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/ideogram_sdk.py
Labels: feature

#268 feat: recraft
  README.md
  assets/recraft.svg
  bilive.toml
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/recraft_sdk.py
Labels: feature

#269 feat: amazon titan
  README.md
  assets/aws-color.svg
  bilive.toml
  requirements.txt
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/amazon_sdk.py
Labels: feature

#270 fix: adjust config
  README.md
  scan.sh
  setPath.sh
  src/upload/query_search_suggestion.py
  upload.sh
Labels: enhancement

#272 docs: update docs
  README.md
Labels: documentation

#273 build: docker 0.3.0
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  logs/record/.gitkeep
  record.sh
  settings.toml
  start.sh
Labels: build

#275 fix: set pwd
  README.md
  record.sh
Labels: enhancement

#277 docs: update docs
  README.md
  docs/.vitepress/config.mts
  docs/biliup.md
  docs/getting-started.md
  docs/index.md
  docs/install-questions.md
  docs/installation.md
  docs/models.md
  docs/record.md
  docs/reference.md
  docs/scan.md
  docs/test-hardware.md
  docs/upload.md
Labels: documentation

#280 feat: sensenova and unittest
  README.md
  assets/sensenova-brand-color.svg
  bilive.toml
  src/autoslice/mllm_sdk/gemini_new_sdk.py
  src/autoslice/mllm_sdk/gemini_old_sdk.py
  src/autoslice/mllm_sdk/qwen_sdk.py
  src/autoslice/mllm_sdk/sensenova_sdk.py
  src/autoslice/mllm_sdk/zhipu_sdk.py
  src/autoslice/title_generator.py
  src/config.py
  tests/__init__.py
  tests/test_autoslice.py
Labels: enhancement, feature

#281 feat: hidream i1
  README.md
  assets/hidream-color.svg
  bilive.toml
  docs/getting-started.md
  src/config.py
  src/cover/cover_generator.py
  src/cover/image_model_sdk/hidream_sdk.py
Labels: feature

#282 test: generate cover
  README.md
  tests/test_cover.py
Labels: enhancement

#284 build: release docker 0.3.0
  .dockerignore
  start.sh
Labels: build

#285 build: release gpu version 0.3.0
  Dockerfile-GPU
  README.md
  docs/installation.md
Labels: build

#291 fix: expand exception
  src/burn/render_video.py
Labels: bug fix

#297 修复merge模式下报错问题
  src/burn/render_then_merge.py
Labels: bug fix

#303 build: release version 0.3.1
  README.md
  compose.yml
  docs/installation.md
Labels: build

#305 ci: add dependabot
  .github/dependbot.yml
Labels: dependencies

#307 ci: add pip check action
  .github/workflows/test.yml
  requirements.txt
Labels: enhancement, dependencies
